/**
 * This function listens to a GitHub PUSH event in order to
 * create/update an OpenWhisk function on each push.
 * Sample payload:
 * {
  "ref": "req-val-upgrade",
  "ref_type": "branch",
  "pusher_type": "user",
  "repository": {
    "id": 40624779,
    "name": "apigateway",
    "full_name": "adobe-apiplatform/apigateway",
    "owner": {
      "login": "adobe-apiplatform",
      "id": 13855477,
      "avatar_url": "https://avatars.githubusercontent.com/u/13855477?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/adobe-apiplatform",
      "html_url": "https://github.com/adobe-apiplatform",
      "followers_url": "https://api.github.com/users/adobe-apiplatform/followers",
      "following_url": "https://api.github.com/users/adobe-apiplatform/following{/other_user}",
      "gists_url": "https://api.github.com/users/adobe-apiplatform/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/adobe-apiplatform/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/adobe-apiplatform/subscriptions",
      "organizations_url": "https://api.github.com/users/adobe-apiplatform/orgs",
      "repos_url": "https://api.github.com/users/adobe-apiplatform/repos",
      "events_url": "https://api.github.com/users/adobe-apiplatform/events{/privacy}",
      "received_events_url": "https://api.github.com/users/adobe-apiplatform/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/adobe-apiplatform/apigateway",
    "description": "A Performant API Gateway based on NGINX and Openresty",
    "fork": false,
    "url": "https://api.github.com/repos/adobe-apiplatform/apigateway",
    "forks_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/forks",
    "keys_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/teams",
    "hooks_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/hooks",
    "issue_events_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/issues/events{/number}",
    "events_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/events",
    "assignees_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/assignees{/user}",
    "branches_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/branches{/branch}",
    "tags_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/tags",
    "blobs_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/languages",
    "stargazers_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/stargazers",
    "contributors_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/contributors",
    "subscribers_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/subscribers",
    "subscription_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/subscription",
    "commits_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/contents/{+path}",
    "compare_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/merges",
    "archive_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/downloads",
    "issues_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/issues{/number}",
    "pulls_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/labels{/name}",
    "releases_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/releases{/id}",
    "deployments_url": "https://api.github.com/repos/adobe-apiplatform/apigateway/deployments",
    "created_at": "2015-08-12T21:17:00Z",
    "updated_at": "2016-10-15T05:07:00Z",
    "pushed_at": "2016-10-18T23:43:22Z",
    "git_url": "git://github.com/adobe-apiplatform/apigateway.git",
    "ssh_url": "git@github.com:adobe-apiplatform/apigateway.git",
    "clone_url": "https://github.com/adobe-apiplatform/apigateway.git",
    "svn_url": "https://github.com/adobe-apiplatform/apigateway",
    "homepage": "",
    "size": 133,
    "stargazers_count": 109,
    "watchers_count": 109,
    "language": "Lua",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 21,
    "mirror_url": null,
    "open_issues_count": 7,
    "forks": 21,
    "open_issues": 7,
    "watchers": 109,
    "default_branch": "master"
  },
  "organization": {
    "login": "adobe-apiplatform",
    "id": 13855477,
    "url": "https://api.github.com/orgs/adobe-apiplatform",
    "repos_url": "https://api.github.com/orgs/adobe-apiplatform/repos",
    "events_url": "https://api.github.com/orgs/adobe-apiplatform/events",
    "hooks_url": "https://api.github.com/orgs/adobe-apiplatform/hooks",
    "issues_url": "https://api.github.com/orgs/adobe-apiplatform/issues",
    "members_url": "https://api.github.com/orgs/adobe-apiplatform/members{/member}",
    "public_members_url": "https://api.github.com/orgs/adobe-apiplatform/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/13855477?v=3",
    "description": null
  },
  "sender": {
    "login": "ddragosd",
    "id": 541933,
    "avatar_url": "https://avatars.githubusercontent.com/u/541933?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ddragosd",
    "html_url": "https://github.com/ddragosd",
    "followers_url": "https://api.github.com/users/ddragosd/followers",
    "following_url": "https://api.github.com/users/ddragosd/following{/other_user}",
    "gists_url": "https://api.github.com/users/ddragosd/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ddragosd/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ddragosd/subscriptions",
    "organizations_url": "https://api.github.com/users/ddragosd/orgs",
    "repos_url": "https://api.github.com/users/ddragosd/repos",
    "events_url": "https://api.github.com/users/ddragosd/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ddragosd/received_events",
    "type": "User",
    "site_admin": false
  }
}
 * @param params The GitHub event
 * @returns {{payload: string}}
 */
function main(params) {
    var name = params.name || "World";
    return {payload: "Hello, " + name + "!"};
}